a,b,c=int(input('Введите число a? ')),int(input('Введите число b? ')),int(input('Введите число c? '))
print ('Резулитат сложения чисел =', end=' ')
print (a+b+c)
print ('Резулитат произведения чисел =', end=' ')
print (a*b*c)